### ISSUE TITLE
Rendering styles in custom tags

### ISSUE THREAD

**Issue by jrans** [dwyl/hapi-riot#11]
`riot.render` strips out all css and from custom tags and therefore lose any tag stylesheets

As riot offers and even recommends adding style sheets to tags to keep them modular shall we offer this feature? 

a suggested solution can be found [here](https://github.com/riot/riot/issues/1250)

I personally love styles within tags so to have this feature would be pretty cool.

**Comment by jrans** [comment]
@nelsonic this process would want to be cached

**Comment by jrans** [comment]
@nelsonic 

A quick simple example of this in action would be to add to https://github.com/dwyl/hapi-riot/blob/master/lib/index.js#L51

```
    output += '<style>';
    output += Riot.compile(require('fs').readFileSync(renderOpts.filename, 'utf8'), { entities: true })[0].css;
    output += '</style>'
```

but as I said we would want to be slightly more clever.

**Comment by nelsonic** [comment]
@jrans give it a go. 👍

**Comment by jrans** [comment]
excited about this
