### ISSUE TITLE
Saturate rendered html with new instances of tag on client

### ISSUE THREAD

**Issue by jackcarlisle** [dwyl/hapi-riot#13]
At the moment front end js isn't supported. We will need to replace the html with new instances of the tags with the same context.

**Comment by nelsonic** [comment]
@jackcarlisle is this front-end JS or CSS...?

**Comment by jackcarlisle** [comment]
@nelsonic front-end JS but it can be compiled in the same way CSS is

**Comment by jackcarlisle** [comment]
@nelsonic this was for front end JS but at the time we were employing the same principle as you would to include CSS. This has been changed now because we're pre-compiling everything

**Comment by jrans** [comment]
done with #17
