### ISSUE TITLE
File Pre-Compilation 

### ISSUE THREAD

**Issue by jackcarlisle** [dwyl/hapi-riot#18]
We can approach this in a couple of ways:

In options passed to the module the user will need to specify where their compiled tags should live. The options are: 
1. Command line compiling - instruct the user to compile the file themselves using a riot command using the same filepath as specified above. 
2. In-built compilation - we could compile the file for them in the hapi-riot compile function if they specify an output filename and path to their views folder as a `mergedOpts`.

@nelsonic what are your thoughts?

**NOTE:** either way, the user will give us the path to their compiled file. The question is mainly - do we want to handle the file compilation or should we let them handle it themselves?

**Comment by jackcarlisle** [comment]
Going with option 1 as it is more simple. Giving instructions in the README for how to implement it correctly

**Comment by jrans** [comment]
closed with #17
