### ISSUE TITLE
Fix todo example

### ISSUE THREAD

**Issue by jrans** [dwyl/hapi-riot#26]
Make todo fully functional and share

**Comment by nelsonic** [comment]
Yeah, at present when we run: the [`/example/WiP_todo/server.js`](https://github.com/dwyl/hapi-riot/blob/86e0f3c16dd647a06d4b711bb93de2df67490633/example/WiP_todo/server.js) by executing the command: `node example/WiP_todo/server.js` and open the browser we see:
![hapi-riot-wip_todo-blank](https://cloud.githubusercontent.com/assets/194400/19621778/4b760428-9891-11e6-93ee-390a08040884.png)
[`blank space`](https://youtu.be/e-ORhEE9VVg) ...

**Comment by rof20004** [comment]
Hi all, I see that in WIP_todo, in server.js, you have called bundle.js, but in the folder name of file is "compile.js", maybe this causing the error ?
