### ISSUE TITLE
Version Bump 

### ISSUE THREAD

**Issue by jackcarlisle** [dwyl/hapi-riot#27]
We should bump the version number up and publish a new version to npm as there have been a number of breaking changes since the last publish.
- [x] bump up the version to 2.0.0 and then publish to npm

**Comment by nelsonic** [comment]
@jackcarlisle the _reason_ I did not release a new version was because we are still waiting on the #26 to _confirm_ that it's all working ... but we can always release _another_ version later ... 😉

**Comment by jackcarlisle** [comment]
@nelsonic ahh sorry!!

**Comment by jrans** [comment]
this is done
