### ISSUE TITLE
Stricter rules on what should be in view folder

### ISSUE THREAD

**Issue by jrans** [dwyl/hapi-riot#29]
We need to only require `.tag` files from the view folder to avoid requiring in any files that error on a require. Alternatively we need to make it clear that people should only put their tags in this folder.

**Comment by rof20004** [comment]
@jrans Hi, I have a question to do, but i think is not needed to create an issue for that, How can I ask something about this project ?

**Comment by jackcarlisle** [comment]
@rof20004 have a look through the dwyl contribution guidelines for raising issues and asking questions -> [guidelines](https://github.com/dwyl/contributing) 

If you want to ask a question, search through the existing issues for keywords that match what you want to ask. If there are no results then open a new issue with your question as the title and give it the `question` label.

**Comment by jackcarlisle** [comment]
@rof20004 when creating a new issue, click the link at the top of the page to take you to these guidelines 👍 
![screen shot 2016-10-27 at 09 18 07](https://cloud.githubusercontent.com/assets/12450298/19759804/7892f342-9c26-11e6-987c-bcf2c2d8dc84.png)

**Comment by rof20004** [comment]
@jackcarlisle ok.
