### ISSUE TITLE
How do people/projects organise their views/components? (Do we need to recursively require templates in sub-directories?)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hapi-riot#3]
At present our `loadTags` method only `requires` the templates in the _current_ directory. 
Do people tend to organise their components using sub-directories e.g: for a hypothetical blog:

``` sh
views
  admin
  auth
  compose
  comments
    form
```

**Comment by rof20004** [comment]
I organize my project like this:

**Comment by rof20004** [comment]
I organize my project like this: ``` ```
