### ISSUE TITLE
State Management [question]

### ISSUE THREAD

**Issue by rof20004** [dwyl/hapi-riot#30]
My question is about State Management.

I know that is possible to do with Riot and Redux.

But in this case when hapi-riot work with layout template(with < < < RIOT > > >), is need some plugin ?

**Comment by jrans** [comment]
Good question. I would do a combination of storing your state in local storage and sending some with you with each page. Then you would want to set up your redux store when the javascript kicks in as a script in your riot tag, taking what you may have saved form local storage... 

So far we don't need to do this yet in our app but if you want to give it a go and create the minimal possible example then please do! and make a PR!
