### ISSUE TITLE
Simple Web App with Login, Register and Route -  Stack HapiJS + RiotJS

### ISSUE THREAD

**Issue by rof20004** [dwyl/hapi-riot#31]
Hi all,

I created a web application with register an user, login and simple route, I will share with the hapi-riot team and ask to see if I made a mistakes with security and good habits. I think that only routes that I can not use, I did not understand yet.

```
1. git clone https://github.com/rof20004/stack-hapi-riot.git
2. npm install && bower install
3. npm start
```

I will wait for impressions, thanks and regards, I liked so much of this hapi-riot plugin.

Rodolfo Azevedo.

**Comment by jrans** [comment]
@rof20004 great, glad to see you put the module to use. Busy this week but will hopefully find some time to look over it on the weekend 😄

**Comment by rof20004** [comment]
I made changes to code,
