### ISSUE TITLE
Require within <script> tags

### ISSUE THREAD

**Issue by jackcarlisle** [dwyl/hapi-riot#35]
In order to make use of external modules by requiring them, hapi-riot should be able to compile these modules so that they are available to our tags. Should we add this functionality?

**Comment by jrans** [comment]
@jackcarlisle So having looked at this, I think its better that we let developers handle this themselves. We are already asking them to compile and serve up their tag bundle and it is at this point that we the requires should be handled by something like webpack. We should though add to the examples a version that uses requires and the right compiler. @nelsonic thoughts?
