### ISSUE TITLE
Should/Can we update Riot.js from 2.6.1 -> 3.0.5 ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hapi-riot#36]
@jackcarlisle / @jrans _can_ we upgrade/update to the latest version of Riot 
(_I ask because AS is our most "sophisticated" project using Riot.js and it would be good to know if_)
https://david-dm.org/dwyl/hapi-riot [![dependencies Status](https://david-dm.org/dwyl/hapi-riot/status.svg)](https://david-dm.org/dwyl/hapi-riot)
Would one of you mind _investigating_ when we get back to work in Jan...? (_thanks!_) ❤️

**Comment by jrans** [comment]
@nelsonic ill get on it before the new year!
