### ISSUE TITLE
missing link in Readme

### ISSUE THREAD

**Issue by Jbarget** [dwyl/hapi-riot#6]
under the WHY heading it says

> please see here:

but missing a link to anything

**Comment by nelsonic** [comment]
![missing link](https://cloud.githubusercontent.com/assets/194400/18395729/c68635bc-76b7-11e6-85bf-9c910e25deca.png)

I'm glad _someone_'s paying attention... 😜 
(_how are **you** JB_...?)

**Comment by nelsonic** [comment]
@Jbarget see: https://github.com/dwyl/hapi-riot#why (_link added_) 👍
